# Generated by Django 5.2.6 on 2025-09-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='library.author')),
            ],
        ),
    ]
